@startuml
set namespaceSeparator ?
hide circle
hide class fields

package IG #DDDDDD{

     package Profiles #DDDDDD{

        class GAP_BundleResultatReponseADemandeConsultationDisponibilite{

             Bundle.type => [None..None]
             Bundle.entry => [None..None]
             Bundle.entry:Slot => [0..*]
             Bundle.entry:Slot.resource => [1..None]
             Bundle.entry:Slot.search.mode => [None..None]
             Bundle.entry:Slot.request => [None..0]
             Bundle.entry:Slot.response => [None..0]
             Bundle.entry:Schedule => [0..*]
             Bundle.entry:Schedule.resource => [1..None]
             Bundle.entry:Schedule.search.mode => [None..None]
             Bundle.entry:Schedule.request => [None..0]
             Bundle.entry:Schedule.response => [None..0]
             Bundle.entry:Patient => [0..*]
             Bundle.entry:Patient.resource => [1..None]
             Bundle.entry:Patient.search.mode => [None..None]
             Bundle.entry:Patient.request => [None..0]
             Bundle.entry:Patient.response => [None..0]
             Bundle.entry:Practitioner => [0..*]
             Bundle.entry:Practitioner.resource => [1..None]
             Bundle.entry:Practitioner.search.mode => [None..None]
             Bundle.entry:Practitioner.request => [None..0]
             Bundle.entry:Practitioner.response => [None..0]
             Bundle.entry:PractitionerRole => [0..*]
             Bundle.entry:PractitionerRole.resource => [1..None]
             Bundle.entry:PractitionerRole.search.mode => [None..None]
             Bundle.entry:PractitionerRole.request => [None..0]
             Bundle.entry:PractitionerRole.response => [None..0]
             Bundle.entry:Device => [0..*]
             Bundle.entry:Device.resource => [1..None]
             Bundle.entry:Device.search.mode => [None..None]
             Bundle.entry:Device.request => [None..0]
             Bundle.entry:Device.response => [None..0]
             Bundle.entry:Location => [0..*]
             Bundle.entry:Location.resource => [1..None]
             Bundle.entry:Location.search.mode => [None..None]
             Bundle.entry:Location.request => [None..0]
             Bundle.entry:Location.response => [None..0]
             Bundle.entry:HealthcareService => [0..*]
             Bundle.entry:HealthcareService.resource => [1..None]
             Bundle.entry:HealthcareService.search.mode => [None..None]
             Bundle.entry:HealthcareService.request => [None..0]
             Bundle.entry:HealthcareService.response => [None..0]
             Bundle.entry:Organization => [0..*]
             Bundle.entry:Organization.resource => [1..None]
             Bundle.entry:Organization.search.mode => [None..None]
             Bundle.entry:Organization.request => [None..0]
             Bundle.entry:Organization.response => [None..0]
             Bundle.entry:RelatedPerson => [0..*]
             Bundle.entry:RelatedPerson.resource => [1..None]
             Bundle.entry:RelatedPerson.search.mode => [None..None]
             Bundle.entry:RelatedPerson.request => [None..0]
             Bundle.entry:RelatedPerson.response => [None..0]
        } 

        class GAP_BundleResultatReponseADemandeConsultationRDV{

             Bundle.type => [None..None]
             Bundle.entry => [None..None]
             Bundle.entry:Appointment => [0..*]
             Bundle.entry:Appointment.resource => [1..None]
             Bundle.entry:Appointment.search.mode => [None..None]
             Bundle.entry:Appointment.request => [None..0]
             Bundle.entry:Appointment.response => [None..0]
             Bundle.entry:Slot => [0..*]
             Bundle.entry:Slot.resource => [1..None]
             Bundle.entry:Slot.search.mode => [None..None]
             Bundle.entry:Slot.request => [None..0]
             Bundle.entry:Slot.response => [None..0]
             Bundle.entry:Schedule => [0..*]
             Bundle.entry:Schedule.resource => [1..None]
             Bundle.entry:Schedule.search.mode => [None..None]
             Bundle.entry:Schedule.request => [None..0]
             Bundle.entry:Schedule.response => [None..0]
             Bundle.entry:Patient => [0..*]
             Bundle.entry:Patient.resource => [1..None]
             Bundle.entry:Patient.search.mode => [None..None]
             Bundle.entry:Patient.request => [None..0]
             Bundle.entry:Patient.response => [None..0]
             Bundle.entry:Practitioner => [0..*]
             Bundle.entry:Practitioner.resource => [1..None]
             Bundle.entry:Practitioner.search.mode => [None..None]
             Bundle.entry:Practitioner.request => [None..0]
             Bundle.entry:Practitioner.response => [None..0]
             Bundle.entry:PractitionerRole => [0..*]
             Bundle.entry:PractitionerRole.resource => [1..None]
             Bundle.entry:PractitionerRole.search.mode => [None..None]
             Bundle.entry:PractitionerRole.request => [None..0]
             Bundle.entry:PractitionerRole.response => [None..0]
             Bundle.entry:Device => [0..*]
             Bundle.entry:Device.resource => [1..None]
             Bundle.entry:Device.search.mode => [None..None]
             Bundle.entry:Device.request => [None..0]
             Bundle.entry:Device.response => [None..0]
             Bundle.entry:Location => [0..*]
             Bundle.entry:Location.resource => [1..None]
             Bundle.entry:Location.search.mode => [None..None]
             Bundle.entry:Location.request => [None..0]
             Bundle.entry:Location.response => [None..0]
             Bundle.entry:HealthcareService => [0..*]
             Bundle.entry:HealthcareService.resource => [1..None]
             Bundle.entry:HealthcareService.search.mode => [None..None]
             Bundle.entry:HealthcareService.request => [None..0]
             Bundle.entry:HealthcareService.response => [None..0]
             Bundle.entry:Organization => [0..*]
             Bundle.entry:Organization.resource => [1..None]
             Bundle.entry:Organization.search.mode => [None..None]
             Bundle.entry:Organization.request => [None..0]
             Bundle.entry:Organization.response => [None..0]
             Bundle.entry:RelatedPerson => [0..*]
             Bundle.entry:RelatedPerson.resource => [1..None]
             Bundle.entry:RelatedPerson.search.mode => [None..None]
             Bundle.entry:RelatedPerson.request => [None..0]
             Bundle.entry:RelatedPerson.response => [None..0]
        } 

        class GAP_FrAppointment{

             Appointment => [None..None]
        } 

        class GAP_FrSchedule{

             Schedule => [None..None]
        } 

        class GAP_FrSlot{

             Slot => [None..None]
         }

     }
     package extension #paleturquoise {


         }
     }
     package valueset #PaleVioletRed{
       }

package "Ressources de base" #palegreen {

 class "Bundle" as  class94c51f19c37f96ed231f5a0ae512b2a8 

    class94c51f19c37f96ed231f5a0ae512b2a8 --> GAP_BundleResultatReponseADemandeConsultationDisponibilite

 class "Bundle" as  class94c51f19c37f96ed231f5a0ae512b2a8 

    class94c51f19c37f96ed231f5a0ae512b2a8 --> GAP_BundleResultatReponseADemandeConsultationRDV

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-appointment" as  class5b3e4ec90388039f3b23e1c44137e12e 

    class5b3e4ec90388039f3b23e1c44137e12e --> GAP_FrAppointment

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-schedule" as  class7c912eb91080e8d9a809e267903ad8a9 

    class7c912eb91080e8d9a809e267903ad8a9 --> GAP_FrSchedule

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-slot" as  classf72d01e910d5b05afa3e849c0230ac33 

    classf72d01e910d5b05afa3e849c0230ac33 --> GAP_FrSlot
}
@enduml